# Generated by Django 5.1.5 on 2025-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.IntegerField()),
                ('name_authors', models.CharField(max_length=150, verbose_name='Автор')),
                ('salary', models.IntegerField()),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('year', models.IntegerField()),
                ('award_name', models.CharField(max_length=150, verbose_name='Награды')),
            ],
            options={
                'db_table': 'hh_testauthor',
            },
        ),
    ]
