names = [
    "Alice", "Ava", "Amelia", "Ben", "Bobby", "Blake", "Clara", "Chloe", "Catherine",
    "Daniel", "David", "Derek", "Emma", "Ella", "Emily", "Frank", "Finn", "Felix",
    "Grace", "Gina", "Gabrielle", "Harry", "Henry", "Harrison", "Ivy", "Isla", "Indigo",
    "Jack", "James", "Jacob", "Kara", "Katherine", "Kim", "Liam", "Leo", "Lucas", "Maya",
    "Megan", "Molly", "Nathan", "Noah", "Nick", "Olivia", "Olga", "Opal", "Paul", "Peter",
    "Philip", "Quinn", "Quincy", "Quentin", "Rachel", "Rose", "Riley", "Sam", "Simon",
    "Seth", "Tara", "Tina", "Tracy", "Ursula", "Uma", "Unity", "Victor", "Vince", "Vladimir",
    "Wendy", "Willow", "Willa", "Xander", "Xena", "Xavier", "Yara", "Yasmine", "Yvonne",
    "Zane", "Zara", "Zoe", "Abigail", "Addison", "Bradley", "Brandon", "Brayden", "Cleo",
    "Carla", "Caroline", "Diana", "Daphne", "Delilah", "Eva", "Ellie", "Elizabeth", "Freya",
    "Fiona", "Francesca", "George", "Grant", "Greg", "Hannah", "Heather", "Holly", "Iris",
    "Irene", "Inez", "Jackie", "Jessica", "Julia", "Kelsey", "Kara", "Kaitlyn", "Lily", "Luna",
    "Leah", "Matthew", "Michael", "Mark", "Nina", "Natalie", "Noelle", "Owen", "Oscar",
    "Orlando", "Penny", "Paige", "Phoebe", "Quincy", "Quintin", "Ruben", "Riley", "Rita",
    "Sophia", "Samantha", "Sarah", "Travis", "Tim", "Tom", "Ulysses", "Ulric", "Umar",
    "Victoria", "Vera", "Vanessa", "Will", "Wesley", "Walter", "Xena", "Xander", "Xenon",
    "Yvette", "Yolanda", "Yara", "Zara", "Zane", "Zaylee"
]

universities = [
    "Harvard University", "Stanford University", "Massachusetts Institute of Technology",
    "University of Oxford", "University of Cambridge", "California Institute of Technology",
    "Princeton University", "Columbia University", "Yale University", "University of Chicago",
    "Imperial College London", "University of California, Berkeley", "University of Toronto",
    "University College London", "ETH Zurich", "University of California, Los Angeles",
    "University of Edinburgh", "University of Michigan", "University of Melbourne", "University of Sydney",
    "Peking University", "Tsinghua University", "University of Hong Kong", "Australian National University",
    "Seoul National University", "University of Tokyo", "National University of Singapore",
    "University of California, San Diego", "New York University", "University of Pennsylvania",
    "University of California, San Francisco", "University of Wisconsin-Madison", "University of Bristol",
    "London School of Economics and Political Science", "University of Amsterdam", "McGill University",
    "University of Zurich", "University of Paris-Sorbonne", "University of California, Irvine",
    "University of Southern California", "University of British Columbia", "University of Washington",
    "University of Copenhagen", "University of Berlin", "University of Delhi", "University of Cape Town",
    "University of Sao Paulo", "University of Delhi", "University of Buenos Aires", "University of Vienna",
    "University of Helsinki", "University of Alberta", "University of Queensland",
    "University of Warwick", "University of Auckland", "King's College London", "University of Freiburg",
    "University of Montreal", "University of Southampton", "University of Munich", "University of Oslo",
    "University of Amsterdam", "University of Frankfurt", "University of Paris", "University of St Andrews",
    "University of Glasgow", "University of North Carolina", "University of Iowa", "University of Minnesota",
    "University of Utah", "University of Pennsylvania", "University of Florida", "University of California, Santa Barbara",
    "Washington University in St. Louis", "Northwestern University", "University of Virginia", "University of Indiana",
    "Boston University", "University of Maryland", "University of Kansas", "Indiana University Bloomington",
    "Purdue University", "University of Pittsburgh", "University of Texas at Austin", "Duke University",
    "University of Miami", "University of Wisconsin", "University of Colorado Boulder", "University of Illinois",
    "Michigan State University", "Ohio State University", "University of Georgia", "University of Missouri",
    "University of Arkansas", "University of Kentucky", "Pennsylvania State University", "University of Connecticut",
    "University of Nebraska-Lincoln", "University of Oklahoma", "University of South Carolina", "University of Tennessee",
    "University of Washington", "University of Rhode Island", "University of Florida", "University of Kansas",
    "University of Wyoming", "University of Nevada, Reno", "University of New Hampshire", "University of Vermont"
]

salaries = [
    50000, 55000, 60000, 65000, 70000, 75000, 80000, 85000, 90000, 95000,
    100000, 105000, 110000, 115000, 120000, 125000, 130000, 135000, 140000, 145000,
    150000, 155000, 160000, 165000, 170000, 175000, 180000, 185000, 190000, 195000,
    200000, 210000, 220000, 230000, 240000, 250000, 260000, 270000, 280000, 290000,
    300000, 310000, 320000, 330000, 340000, 350000, 360000, 370000, 380000, 390000,
    400000, 420000, 440000, 460000, 480000, 500000, 520000, 540000, 560000, 580000,
    600000, 620000, 640000, 660000, 680000, 700000, 720000, 740000, 760000, 780000,
    800000, 820000, 840000, 860000, 880000, 900000, 920000, 940000, 960000, 980000,
    1000000, 1050000, 1100000, 1150000, 1200000, 1250000, 1300000, 1350000, 1400000, 1450000,
    1500000, 1550000, 1600000, 1650000, 1700000, 1750000, 1800000, 1850000, 1900000, 1950000,
    2000000, 2050000, 2100000, 2150000, 2200000, 2250000, 2300000, 2350000, 2400000, 2450000,
    2500000, 2550000, 2600000, 2650000, 2700000, 2750000, 2800000, 2850000, 2900000, 2950000,
    3000000, 3050000, 3100000, 3150000, 3200000, 3250000, 3300000, 3350000, 3400000, 3450000
]

author_positions = [
    "Novelist", "Poet", "Essayist", "Playwright", "Screenwriter", "Journalist",
    "Columnist", "Biographer", "Memoirist", "Critic", "Editor", "Publisher",
    "Literary Agent", "Copywriter", "Content Writer", "Technical Writer",
    "Ghostwriter", "Storyteller", "Scriptwriter", "Travel Writer", "Food Critic",
    "Fashion Writer", "Blogger", "Influencer", "Speechwriter", "Academic Writer",
    "Researcher", "Science Writer", "History Author", "Philosophy Writer", "Political Writer",
    "Fiction Writer", "Non-Fiction Writer", "Children's Author", "Young Adult Author",
    "Romance Writer", "Thriller Author", "Mystery Writer", "Fantasy Author", "Science Fiction Writer",
    "Horror Writer", "Historical Fiction Author", "Crime Novelist", "Self-Help Author", "Health Writer",
    "Parenting Writer", "Business Author", "Economics Writer", "Technology Author", "Motivational Speaker",
    "Poetry Editor", "Book Reviewer", "Literary Critic", "Publishing Consultant", "Press Release Writer",
    "Translational Writer", "Speech Writer", "Anthologist", "Journal Editor", "Literary Historian",
    "Cultural Commentator", "Magazine Writer", "Newspaper Columnist", "Art Critic", "Media Correspondent",
    "Graphic Novelist", "Comic Book Writer", "Adventure Writer", "Satirical Writer", "Short Story Author",
    "Literary Translator", "Pseudonymous Author", "Screenplay Consultant", "Writing Coach", "Narrative Designer",
    "Dialogue Writer", "Book Blogger", "Literary Event Speaker", "Social Media Writer", "Publishing Editor",
    "Book Publisher", "Writing Mentor", "Fiction Editor", "Essay Editor", "Video Game Writer",
    "Interactive Storyteller", "Creative Director", "Writer-In-Residence", "Press Editor", "Journalism Educator",
    "Documentary Writer", "Film Consultant", "Podcast Writer", "Technical Manual Writer", "Brand Journalist",
    "Advertorial Writer", "Academic Researcher", "Science Fiction Editor", "Book Designer", "Literary Agent Assistant",
    "Film Adaptation Writer", "Literary Festival Speaker", "Literary Magazine Editor", "Content Strategist", "Travel Blogger"
]


literary_awards = [
    "Нобелевская премия по литературе", "Пулитцеровская премия", "Букеровская премия",
    "Литературная премия имени А. П. Чехова", "Литературная премия имени И. А. Бунина",
    "Литературная премия имени Ф. М. Достоевского", "Литературная премия имени М. А. Шолохова",
    "Литературная премия имени А. С. Пушкина", "Литературная премия имени Н. В. Гоголя",
    "Литературная премия имени В. Г. Белинского", "Литературная премия имени А. И. Солженицына",
    "Литературная премия имени Бориса Пастернака", "Литературная премия имени Анны Ахматовой",
    "Литературная премия имени Иосифа Бродского", "Литературная премия имени Александра Блока",
    "Литературная премия имени Сергея Есенина", "Литературная премия имени Михаила Зощенко",
    "Литературная премия имени Валентина Распутина", "Литературная премия имени Виктора Пелевина",
    "Литературная премия имени Людмилы Улицкой", "Литературная премия имени Григория Остермана",
    "Литературная премия имени Ивана Тургенева", "Литературная премия имени Константина Паустовского",
                   "Литературная премия имени Михаила Шолохова", "Литературная премия имени Василия Шукшина",
                   "Литературная премия имени Александра Солженицына", "Литературная премия имени Бориса Гребенщикова",
                   "Литературная премия имени Сергея Довлатова", "Литературная премия имени Виктора Шкловского",
                   "Литературная премия имени Игоря Бабкова", "Литературная премия имени Анатолия Кузнецова",
                   "Литературная премия имени Валентина Григорьева", "Литературная премия имени Юрия Дружкова",
                   "Литературная премия имени Алексея Толстого", "Литературная премия имени Игоря Севера",
                   "Литературная премия имени Анатолия Приставкина", "Литературная премия имени Валентина Распутина",
                   "Литературная премия имени Игоря Крутого", "Литературная премия имени Сергея Лукьяненко",
                   "Литературная премия имени Дмитрия Быкова", "Литературная премия имени Александра Блока",
                   "Литературная премия имени Игоря Губермана", "Литературная премия имени Анатолия Кузнецова",
                   "Литературная премия имени Валентина Григорьева", "Литературная премия имени Юрия Дружкова",
                   "Литературная премия имени Алексея Толстого", "Литературная премия имени Игоря Севера",
                   "Литературная премия имени Анатолия Приставкина", "Литературная премия имени Валентина Распутина",
                   "Литературная премия имени Игоря Крутого", "Литературная премия имени Сергея Лукьяненко",
                   "Литературная премия имени Дмитрия Быкова", "Литературная премия имени Александра Блока",
                   "Литературная премия имени Игоря Губермана", "Литературная премия имени Анатолия Кузнецова",
                   "Литературная премия имени Валентина Григорьева", "Литературная премия имени Юрия Дружкова",
                   "Литературная премия имени Алексея Толстого", "Литературная премия имени Игоря Севера",
                   "Литературная премия имени Анатолия Приставкина", "Литературная премия имени Валентина Распутина"]
